---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать
    подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и
    просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и
    оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность зарегистрироваться и авторизоваться на
    сайте
  - Пользователь должен иметь возможность отслеживать оформленный заказ
  - На сайте должна быть форма обратной связи для обращения в тех поддержку
  - Пользователь должен иметь возможность редактировать количество добавленных
    товаров в корзине
  - На сайте должна быть указана контактная информация продавца
  - Пользователь должен иметь возможность фильтровать товары по возрастанию и
    убыванию цены
  - Пользователь должен иметь возможность фильтровать товары по рейтингу
  - Рядом с названием товара в корзине должно отображаться также изображение
    товара
  - У сайта должна быть адаптивная верстка
